Updates icon sizes to be the same size/type as Steam
AsherGlick/ResourceCalculator pull request #68
Opened 2022-06-09 22:12 UTC by vreelb

This should make it really easy to contribute the icon step of a new game. Size-wise the jpg and png files differed based on the image being stored/compressed, some were bigger and some were smaller but they averaged to be about the same size.

* Updates existing icons to those from Steam for Steam games, manually made remaining icons from other sources.
* Updates `README.md` to reflect these changes.
* Updates the step order to have creating the folder first, then simple steps, then the `yaml` at the end.
* CSS changes to support both the new size and also smaller viewscreens:
![image](https://user-images.githubusercontent.com/1118472/172953612-4ebe724d-7a62-4eb6-b78c-40b5503c6764.png)

2022-07-10 14:35 UTC, AsherGlick requested changes

2022-07-10 16:46 UTC, vreelb commented on README.md
> +    * These are the same dimensions as the thumbnail in the Steam store.
Yeah I think that would be helpful. I also want to include a note that we should aim for pictures that aren't temporary for a sale / event and are more general to the game,

2022-07-10 16:52 UTC, vreelb commented on README.md
> +    * These are the same dimensions as the thumbnail in the Steam store.
That Deep Rock example is actually very helpful as it shows that there have been 13 headers so far and you can decrement the number to get earlier ones.

2022-07-10 17:11 UTC, vreelb commented on core/index.html
> +			<a href="./{{calculator.path}}">
Was it a problem when building? I didn't run into any issues when testing this.

2022-07-11 01:15 UTC, AsherGlick commented on core/index.html
> +			<a href="./{{calculator.path}}">
Closing this after offline discussion that this wont effect production but might effect folks using a draft build.

2022-07-11 01:18 UTC, merged